name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    branches: [main, develop]
    types:
      - completed
  release:
    types: [published]
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'release' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=long
      
      - name: Determine target environment
        id: env
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "target=production" >> $GITHUB_OUTPUT
            echo "environment=production" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "target=production" >> $GITHUB_OUTPUT
            echo "environment=staging" >> $GITHUB_OUTPUT
          else
            echo "target=development" >> $GITHUB_OUTPUT
            echo "environment=development" >> $GITHUB_OUTPUT
          fi
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: ${{ steps.env.outputs.target }}
  
  deploy-development:
    name: Deploy to Development
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/develop'
    environment: development
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
      
      - name: Deploy to development server
        env:
          DOCKER_HOST: ${{ secrets.DEV_SERVER_HOST }}
          DOCKER_IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
        run: |
          # Create deployment script
          cat > deploy.sh << 'EOL'
          #!/bin/bash
          set -e
          
          # Pull the latest image
          docker pull ${DOCKER_IMAGE}
          
          # Create or update .env file
          cat > .env << EOF
          MYSQL_ROOT_PASSWORD=${{ secrets.DEV_MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE=api_performance
          MYSQL_USER=api_user
          MYSQL_PASSWORD=${{ secrets.DEV_MYSQL_PASSWORD }}
          EOF
          
          # Deploy using docker-compose
          docker-compose -f docker-compose.yml -f docker-compose.dev.yml down
          docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d
          EOL
          
          # Make script executable
          chmod +x deploy.sh
          
          # Copy files to server
          scp -o StrictHostKeyChecking=no docker-compose.yml docker-compose.dev.yml deploy.sh ${DOCKER_HOST}:~/
          
          # Execute deployment script
          ssh -o StrictHostKeyChecking=no ${DOCKER_HOST} './deploy.sh'
  
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.event_name == 'release'
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
      
      - name: Deploy to production server
        env:
          DOCKER_HOST: ${{ secrets.PROD_SERVER_HOST }}
          DOCKER_IMAGE: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
        run: |
          # Create deployment script
          cat > deploy.sh << 'EOL'
          #!/bin/bash
          set -e
          
          # Pull the latest image
          docker pull ${DOCKER_IMAGE}
          
          # Create or update .env file
          cat > .env << EOF
          MYSQL_ROOT_PASSWORD=${{ secrets.PROD_MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE=api_performance
          MYSQL_USER=api_user
          MYSQL_PASSWORD=${{ secrets.PROD_MYSQL_PASSWORD }}
          EOF
          
          # Deploy using docker-compose
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml down
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
          EOL
          
          # Make script executable
          chmod +x deploy.sh
          
          # Copy files to server
          scp -o StrictHostKeyChecking=no docker-compose.yml docker-compose.prod.yml deploy.sh ${DOCKER_HOST}:~/
          
          # Execute deployment script
          ssh -o StrictHostKeyChecking=no ${DOCKER_HOST} './deploy.sh'

  deploy-lambda:
    name: Deploy to AWS Lambda
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4.0
          virtualenvs-create: true
          virtualenvs-in-project: true
      
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Generate deployment package
        run: |
          # Create a temporary directory for the package
          mkdir -p deployment-package
          
          # Export dependencies
          poetry export -f requirements.txt --without-hashes > requirements.txt
          
          # Install dependencies into the package directory
          pip install -r requirements.txt --target deployment-package
          
          # Copy application code
          cp -r app/* deployment-package/
          
          # Create ZIP file
          cd deployment-package
          zip -r ../lambda-package.zip .
          cd ..
      
      - name: Update Lambda Function
        run: |
          # Extract version from tag
          VERSION=${{ github.ref_name }}
          FUNCTION_NAME=${{ secrets.AWS_LAMBDA_FUNCTION_NAME }}
          
          # Function to check Lambda state with detailed status and conflict handling
          check_lambda_state() {
            echo "Checking Lambda function state..."
            
            # Get function details with error handling and retry for conflicts
            local max_retries=5
            local retry_count=0
            local retry_delay=5
            local backoff_multiplier=2
            
            while [ $retry_count -lt $max_retries ]; do
              FUNCTION_DETAILS=$(aws lambda get-function --function-name $FUNCTION_NAME 2>&1)
              GET_STATUS=$?
              
              if [ $GET_STATUS -eq 0 ]; then
                break
              elif echo "$FUNCTION_DETAILS" | grep -q "ResourceConflictException"; then
                retry_count=$((retry_count + 1))
                if [ $retry_count -lt $max_retries ]; then
                  retry_delay=$((retry_delay * backoff_multiplier))
                  echo "ResourceConflictException detected, retrying in ${retry_delay}s (attempt $retry_count/$max_retries)..."
                  sleep $retry_delay
                  continue
                fi
              fi
              
              echo "Error getting Lambda function details: $FUNCTION_DETAILS"
              return 2
            done
            
            # Extract and validate state information with enhanced error checking
            STATE=$(echo "$FUNCTION_DETAILS" | jq -r '.Configuration.State')
            LAST_UPDATE=$(echo "$FUNCTION_DETAILS" | jq -r '.Configuration.LastUpdateStatus')
            LAST_UPDATE_REASON=$(echo "$FUNCTION_DETAILS" | jq -r '.Configuration.LastUpdateStatusReasonCode')
            CODE_SHA=$(echo "$FUNCTION_DETAILS" | jq -r '.Configuration.CodeSha256')
            FUNCTION_ERROR=$(echo "$FUNCTION_DETAILS" | jq -r '.Configuration.LastUpdateStatusReason')
            
            # Validate extracted values with detailed error reporting
            if [ -z "$STATE" ] || [ "$STATE" = "null" ] || \
               [ -z "$LAST_UPDATE" ] || [ "$LAST_UPDATE" = "null" ]; then
              echo "ERROR: Invalid state information received"
              echo "State: $STATE"
              echo "Last Update: $LAST_UPDATE"
              echo "Function Error: $FUNCTION_ERROR"
              return 5
            fi
            
            echo "Current state: $STATE"
            echo "Last update status: $LAST_UPDATE"
            echo "Last update reason: $LAST_UPDATE_REASON"
            echo "Code SHA: $CODE_SHA"
            if [ ! -z "$FUNCTION_ERROR" ] && [ "$FUNCTION_ERROR" != "null" ]; then
              echo "Function error details: $FUNCTION_ERROR"
            fi
            
            # Enhanced state validation with specific error codes
            case "$STATE" in
              "Failed")
                echo "ERROR: Lambda function is in Failed state"
                echo "Failure reason: $FUNCTION_ERROR"
                return 3
                ;;
              "Pending")
                echo "Lambda function is in Pending state"
                return 1
                ;;
              "Active")
                case "$LAST_UPDATE" in
                  "Failed")
                    echo "ERROR: Last update failed with reason: $LAST_UPDATE_REASON"
                    echo "Error details: $FUNCTION_ERROR"
                    return 4
                    ;;
                  "InProgress")
                    echo "Update is still in progress"
                    return 1
                    ;;
                  "Successful")
                    echo "Lambda function is in desired state"
                    return 0
                    ;;
                  *)
                    echo "WARNING: Unknown last update status: $LAST_UPDATE"
                    return 6
                    ;;
                esac
                ;;
              *)
                echo "WARNING: Unknown function state: $STATE"
                return 7
                ;;
            esac
            
            echo "Lambda function is not in desired state"
            return 1
          }
          
          # Function to wait for Lambda to be ready with enhanced error handling and backoff
          wait_for_lambda_ready() {
            local max_attempts=30
            local initial_wait=10
            local max_wait=60
            local timeout_seconds=300
            local start_time=$(date +%s)
            local consecutive_conflicts=0
            local wait_seconds=$initial_wait
            local last_error=""
            
            echo "Waiting for Lambda function to be ready (timeout: ${timeout_seconds}s)..."
            
            for ((i=1; i<=$max_attempts; i++)); do
              local current_time=$(date +%s)
              local elapsed_time=$((current_time - start_time))
              
              if [ $elapsed_time -ge $timeout_seconds ]; then
                echo "ERROR: Global timeout reached after ${elapsed_time} seconds"
                if [ ! -z "$last_error" ]; then
                  echo "Last error encountered: $last_error"
                fi
                return 2
              fi
              
              check_lambda_state
              local check_status=$?
              
              case $check_status in
                0)
                  echo "SUCCESS: Lambda function is ready after $i attempts (${elapsed_time}s elapsed)"
                  return 0
                  ;;
                1)
                  echo "Attempt $i/$max_attempts: Lambda not ready yet (${elapsed_time}s elapsed)"
                  # Reset conflict counter on non-conflict status
                  consecutive_conflicts=0
                  wait_seconds=$initial_wait
                  ;;
                2)
                  if echo "$FUNCTION_DETAILS" | grep -q "ResourceConflictException"; then
                    consecutive_conflicts=$((consecutive_conflicts + 1))
                    # Enhanced exponential backoff for conflicts
                    wait_seconds=$((initial_wait * 2 ** consecutive_conflicts))
                    if [ $wait_seconds -gt $max_wait ]; then
                      wait_seconds=$max_wait
                    fi
                    echo "ResourceConflictException detected, increasing wait time to ${wait_seconds}s"
                    last_error="ResourceConflictException after $consecutive_conflicts consecutive attempts"
                  else
                    echo "ERROR: Failed to get Lambda status (${elapsed_time}s elapsed)"
                    last_error="$FUNCTION_DETAILS"
                    return 3
                  fi
                  ;;
                3|4)
                  echo "ERROR: Lambda is in failed state (${elapsed_time}s elapsed)"
                  last_error="Function state: $STATE, Last update status: $LAST_UPDATE, Reason: $LAST_UPDATE_REASON"
                  return 4
                  ;;
                5)
                  echo "ERROR: Invalid state information received (${elapsed_time}s elapsed)"
                  last_error="Invalid state data - State: $STATE, Last update: $LAST_UPDATE"
                  return 5
                  ;;
                6|7)
                  echo "WARNING: Unexpected state encountered (${elapsed_time}s elapsed)"
                  last_error="Unexpected state - State: $STATE, Last update: $LAST_UPDATE"
                  # Continue trying as this might be temporary
                  ;;
              esac
              
              # Dynamic wait time calculation based on remaining time
              local remaining_time=$((timeout_seconds - elapsed_time))
              if [ $remaining_time -lt $wait_seconds ]; then
                wait_seconds=$remaining_time
              fi
              
              if [ $wait_seconds -gt 0 ]; then
                echo "Waiting ${wait_seconds} seconds before next attempt... (${remaining_time}s remaining)"
                sleep $wait_seconds
              fi
            done
            
            echo "ERROR: Maximum attempts ($max_attempts) reached after ${elapsed_time}s"
            if [ ! -z "$last_error" ]; then
              echo "Last error encountered: $last_error"
            fi
            return 1
          }
          
          # Initial state check before any updates
          echo "Performing initial Lambda state check..."
          wait_for_lambda_ready
          INITIAL_CHECK_STATUS=$?
          if [ $INITIAL_CHECK_STATUS -ne 0 ]; then
            echo "ERROR: Initial Lambda state check failed with status $INITIAL_CHECK_STATUS"
            exit 1
          fi
          
          # Update Lambda function code with error handling
          echo "Updating Lambda function code..."
          UPDATE_RESULT=$(aws lambda update-function-code \
            --function-name $FUNCTION_NAME \
            --zip-file fileb://lambda-package.zip 2>&1)
          
          if [ $? -ne 0 ]; then
            echo "ERROR: Failed to update Lambda function code: $UPDATE_RESULT"
            exit 1
          fi
          
          # Wait for code update to complete with enhanced error handling
          echo "Waiting for code update to complete..."
          wait_for_lambda_ready
          CODE_UPDATE_STATUS=$?
          if [ $CODE_UPDATE_STATUS -ne 0 ]; then
            echo "ERROR: Code update verification failed with status $CODE_UPDATE_STATUS"
            exit 1
          fi
          
          # Update Lambda configuration with error handling
          echo "Updating Lambda function configuration..."
          CONFIG_UPDATE_RESULT=$(aws lambda update-function-configuration \
            --function-name $FUNCTION_NAME \
            --handler app.main.handler \
            --runtime python3.9 \
            --timeout 30 \
            --memory-size 256 \
            --environment Variables="{
              STAGE=production,
              DB_HOST=${{ secrets.PROD_DB_HOST }},
              DB_PORT=${{ secrets.PROD_DB_PORT }},
              DB_USER=${{ secrets.PROD_DB_USER }},
              DB_PASSWORD=${{ secrets.PROD_DB_PASSWORD }},
              DB_NAME=${{ secrets.PROD_DB_NAME }},
              REDIS_HOST=${{ secrets.PROD_REDIS_HOST }},
              REDIS_PORT=${{ secrets.PROD_REDIS_PORT }}
            }" 2>&1)
          
          if [ $? -ne 0 ]; then
            echo "ERROR: Failed to update Lambda configuration: $CONFIG_UPDATE_RESULT"
            exit 1
          fi
          
          # Wait for configuration update to complete with enhanced error handling
          echo "Waiting for configuration update to complete..."
          wait_for_lambda_ready
          CONFIG_UPDATE_STATUS=$?
          if [ $CONFIG_UPDATE_STATUS -ne 0 ]; then
            echo "ERROR: Configuration update verification failed with status $CONFIG_UPDATE_STATUS"
            exit 1
          fi
          
          # Publish new version with error handling
          echo "Publishing new version..."
          PUBLISH_RESULT=$(aws lambda publish-version \
            --function-name $FUNCTION_NAME \
            --description "Deployment of version $VERSION" 2>&1)
          
          if [ $? -ne 0 ]; then
            echo "ERROR: Failed to publish new version: $PUBLISH_RESULT"
            exit 1
          fi
          
          # Final verification with enhanced error handling
          echo "Performing final verification..."
          wait_for_lambda_ready
          FINAL_STATUS=$?
          if [ $FINAL_STATUS -ne 0 ]; then
            echo "ERROR: Final verification failed with status $FINAL_STATUS"
            exit 1
          fi
          
          echo "SUCCESS: Lambda deployment completed successfully"
          
          # Output final Lambda function state
          echo "Final Lambda function state:"
          check_lambda_state
